- Cargo.toml
- src/error.rs
- src/lib.rs
- src/poly.rs
- Added trait `ContainsSecret`.
- Added `mlock` and `munlock` for secret types.
- Removed stack copying of secret prime field elements.
- Changed `SecretKey(Fr)` to `SecretKey(Box<Fr>)`.
- Added [`memsec`](https://crates.io/crates/memsec) and [`errno`](https://crates.io/crates/errno) dependencies.
- Redacted `Debug` implementations of secrets.
Closes Issue #3
> Added mlocking for secret types.

- .travis.yml
I'm not sure how much if any speedup this gives but there are no drawbacks I'm aware of (unless `lto=true`, which we won't be using).
> Travis: Enable cpu-specific optimizations.

- .travis.yml
- README.md
- benches/bench.rs
This also randomizes the input for every iteration. Otherwise a particularly convenient (e.g. low-degree) input would speed up all iterations and distort the results.
> Benchmark polynomials of different degrees.

- src/lib.rs
- src/poly.rs
Output "..." in the `Debug` implementation of `SecretKeyShare`, to make it consistent with `SecretKey`.
> Use Formatter debug helpers. Hide SecretKeyShares.

- src/poly.rs
This reduces time for interpolation by about 20% on my machine.
Also add more `Mul` implementations.
> Simplify Poly multiplication, speed up interpolation.

- benches/bench.rs
- examples/threshold_enc.rs
- examples/threshold_sig.rs
- src/lib.rs
- src/poly.rs
- Added a set of "try_" prefixed constructors to secret types that can return an `Err` if memory locking fails. The non-"try_" prefixed constructors will panic in the event of a memory locking failure.
- Changed tests to use the non-"try_" prefixed constructors, because tests should be run with `MLOCK_SECRETS=false` and never fail for `mlock` related reasons.
- Improved the docstrings for secret-type constructors to differentiate those that panic from those that return an `Err`.
Closes issue #6
> Added 'try_' constructors to secret types.

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- examples/threshold_enc.rs
- examples/threshold_sig.rs
Minor grammar modifications to examples. I suggest changing 'operatives' to 'actors' for consistency in explanation, even though I like operatives better.
> Typo fixes, added Code of Conduct file

- src/lib.rs
- src/poly.rs
- src/secret.rs
- Moved everything memory related to the `secret` module.
- Added type `Safe<T>` for clearing, locking, and unlocking temporary values that should be kept secret.
- Added temporary value clearing to polynomial multiplication.
- Removed `Poly::extend_mlock(&mut self)` and `Poly::truncate_ mlock(&mut self)` (locking on instantiation and destruction of `Poly` is enough).
Closes issue #24
> Added type for clearing temporary values.

- .travis.yml
`cargo install` fails if it's already installed.
> Fix build failure if deadlinks is already installed.

- src/lib.rs
This is a small API extension that should be fully backwards compatible, but allows libraries to supply their own random number generator when calling `encrypt`.
This will soon be a required feature for `hbbft`, for this reason I would like to see this single change cherry picked for a `0.1.1` release.
> Add an API that allows specifying the RNG to be used for encryption.

- src/error.rs
- src/lib.rs
- src/poly.rs
- src/serde_impl.rs
Fix a few issues pointed out in the code audit:
* `xor_vec` and `hash_bytes` are never used separately, and the API of `xor_vec` is a bit dangerous since it silently stops at the minimum of the two arguments' lengths.
* A polynomial has `degree + 1` coefficients, so creating one with degree `usize::max_value()` panics.
* `BivarPoly` and `BivarCommitment` have an invariant (`coeff.len() == coeff_pos(degree, degree) + 1`), which isn't verified on creation and deserialization.
> Merge xor_vec and hash_bytes, validate polynomial degrees.

- README.md
- src/error.rs
- src/lib.rs
- src/poly.rs
- src/secret.rs
It currently causes too many problems to be practical. We will re-enable it once we have a dedicated allocator for locked memory.
This also removes the `try_` methods for now, because errors are only returned if m[un]locking fails.
> Remove mlock.

- src/error.rs
The `unsafe impl`s are unnecessary.
This adds a test instead to make sure we don't make the errors `!Sync` or `!Send` by mistake in the future.
> Remove explicit Send+Sync impl for Error.

- src/error.rs
- src/lib.rs
- src/mock/mod.rs
- src/serde_impl.rs
This removes the unneeded length from key and signature representation, removing 8 bytes from each. Also adds `from_bytes` and `to_bytes` methods to convert keys and signatures.
Closes #63.
> Make serialization less wasteful.

- src/lib.rs
- src/serde_impl.rs
Fixes #73 . This implements a wrapper struct for secret keys `SerdeSecret` that enables these to be serialized and deserialized. I only intend to implement this for the non-mocked crypto because I didn't find a good generic interface to ser/de the underlying `Fr` struct, so I'm currently just taking the `pub [u64, 4]` out of the `FrRepr`.
> Implement serde for secret keys

- src/serde_impl.rs
Otherwise it's impossible to actually use the wrapper to serialize an existing secret key.
> Make SerdeSecret's field public.

- .travis.yml
- Cargo.toml
- examples/basic_pkc.rs
- src/lib.rs
- src/poly.rs
- src/serde_impl.rs
The upgrade to the latest `serde` and using the `derive` feature reportedly fixed the issue in #78 although I wasn't able to reproduce it.
> Using the serde derive feature instead of the crate serde_derive

- src/lib.rs
The contents would otherwise print three elements of `Fq`, which is very lengthy and possibly even secret information in some cases.
This PR also removes the misleading quotation marks in the `SecretKey[Share]` debug output and now prints `SecretKey(...)` instead of `SecretKey("...")`.
> Hide DecryptionShare contents in Debug output.

- src/lib.rs
That's what the method documentation says. It explicitly warns that it
reveals the secret key, unlike the `Debug` implementation.
An example output from the tests:
```rust
SecretKey(Fr(FrRepr([17796403590321401452, 5186408160561640781, 5316101836953068894, 4215027201736618979])))
```
> Make `reveal` print the secret key, not the public one.

- .travis.yml
- src/lib.rs
> Make SecretKeySet cloneable. Rust 1.42.0.
